module.exports = {
  path: '/shop/recharge.json',
  template: {
    data:{
      zhidahao:-1,
      weixin:0,
      baidu:0,
      alipay:-1,
      ruleInfo:{
        isFullSend:1,
        ruleList:[
          {
            fullValue:100,
          },
          {
            fullValue:500,
          },
        ],
      },
      planRuleList:[
        {
          planId:'6806',
          planName:'储值赠送菜品券',
          planStartDay:'2016-08-18',
          planEndDay:'2016-12-31',
          rules:[
            {
              storeAmount:500.0,
              couponType:3,
              couponName:'红烧排骨1礼品券',
            },
            {
              storeAmount:199.0,
              couponType:1,
              couponName:'测试券哟',
            },
            {
              storeAmount:299.0,
              couponType:2,
              couponName:'123',
            },
          ],
        },
        {
          planId:'6806',
          planName:'储值赠送菜品券',
          planStartDay:'2016-08-18',
          planEndDay:'2016-12-31',
          rules:[
            {
              storeAmount:500.0,
              couponType:3,
              couponName:'红烧排骨1礼品券',
            },
            {
              storeAmount:199.0,
              couponType:1,
              couponName:'测试券哟',
            },
            {
              storeAmount:199.0,
              couponType:1,
              couponName:'测试券哟',
            },
          ],
        },
      ],
    },
    time:1477535714827,
    code:'200',
    msg:'',
  },
};
