exports.singleDishWithoutProps = {
  id: 1218630,
  name: '应季美味蒸饺(6只)',
  type: 0,
  aliasName: '',
  unitId: null,
  unitName: '份',
  marketPrice: 12,
  dishDesc: '',
  videoUrl: '',
  dishIncreaseUnit: 1,
  stepNum: 1,
  currRemainTotal: null,
  dishTypeId: 5971,
  brandDishId: 877587,
  largeImgUrl: 'http://kry-official.qiniudn.com/9c8c8668468a43f2861b7cd50286dcf9.jpg',
  smallImgUrl: 'http://kry-official.qiniudn.com/5f7daa1cbce14dd2a22ea7dc286c9a5c.jpg',
  dishQty: 1,
  boxQty: 1,
  clearStatus: 1,
  dishPropertyTypeInfos: [],
  dishIngredientInfos: [],
};
exports.singleDishWithProps = {
  id: 63251,
  name: '天然白虾芦笋蒸饺3只',
  type: 0,
  aliasName: '',
  unitId: null,
  unitName: '份',
  marketPrice: 21,
  dishDesc: '“赤道之国”的美味馈赠 - 口感紧实、回味甘甜 纯净无污染的漫长海岸线 - 零药残、零激素 Cleaner & Healthier All Natural Shrimp',
  videoUrl: '',
  dishIncreaseUnit: 1,
  stepNum: 1,
  currRemainTotal: null,
  dishTypeId: 5973,
  brandDishId: 139020,
  largeImgUrl: 'http://kry-official.qiniudn.com/5fd9a98e305e44ddbf842f69a2166f3c.jpg',
  smallImgUrl: 'http://kry-official.qiniudn.com/5a9768b3918743d689e8343f4f99ce8d.jpg',
  dishQty: 1,
  boxQty: 1,
  clearStatus: 1,
  dishPropertyTypeInfos: [
    {
      id: 3121,
      name: '口味',
      type: 1,
      properties: [
        {
          id: 11058,
          name: '芝麻粒酱醋汁',
          reprice: 0,
          isChecked: false,
        },
        {
          id: 11061,
          name: '花生碎辣酱汁',
          reprice: 0,
          isChecked: false,
        },
        {
          id: 11064,
          name: '小米椒蒜辣汁',
          reprice: 0,
          isChecked: false,
        },
        {
          id: 11055,
          name: '不配酱汁',
          reprice: 0,
          isChecked: false,
        },
      ],
    },
  ],
  dishIngredientInfos: [],
};
exports.groupDish = {
  id: 1218629,
  name: '单人蒸饺套餐',
  type: 1,
  aliasName: '',
  unitId: null,
  unitName: '份',
  marketPrice: 28,
  dishDesc: '',
  videoUrl: '',
  dishIncreaseUnit: 1,
  stepNum: 1,
  currRemainTotal: null,
  dishTypeId: 54663,
  brandDishId: 877679,
  largeImgUrl: 'http://kry-official.qiniudn.com/bfda15618c7e45b296e0ae7f2afedabc.jpg',
  smallImgUrl: 'http://kry-official.qiniudn.com/67b1c13e56b840e596a645727eace5a4.jpg',
  dishQty: 1,
  boxQty: 1,
  clearStatus: 1,
  order: [
    {
      count:2,
      groups: [
        {
          id: 26363,
          name: '默认分组',
          orderMin: 0,
          orderMax: 2,
          childInfos: [
            {
              id: 938230,
              name: '西葫芦鸡蛋蒸饺(6只)',
              marketPrice: 0,
              leastCellNum: 1,
              isReplace: false,
              isDefault: false,
              isMulti: false,
              brandDishId: 694575,
              dishQty: 1,
              boxQty: 1,
              dishPropertyTypeInfos: [],
              dishIngredientInfos: [],
            },
            {
              id: 1218630,
              name: '应季美味蒸饺(6只)',
              marketPrice: 0,
              leastCellNum: 1,
              isReplace: false,
              isDefault: false,
              isMulti: true,
              brandDishId: 877587,
              dishQty: 1,
              boxQty: 1,
              dishPropertyTypeInfos: [],
              dishIngredientInfos: [],
            },
          ],
        },
        {
          id: 26365,
          name: '小吃饮品',
          orderMin: 0,
          orderMax: 1,
          childInfos: [
            {
              id: 62891,
              name: '竹蔗茅根马蹄水(冷)',
              marketPrice: 0,
              leastCellNum: 1,
              isReplace: false,
              isDefault: false,
              isMulti: true,
              brandDishId: 139139,
              dishQty: 1,
              boxQty: 1,
              dishPropertyTypeInfos: [],
              dishIngredientInfos: [],
            },
            {
              id: 62685,
              name: '爽口脆萝卜',
              marketPrice: 0,
              leastCellNum: 1,
              isReplace: false,
              isDefault: false,
              isMulti: false,
              brandDishId: 138991,
              dishQty: 1,
              boxQty: 1,
              dishPropertyTypeInfos: [],
              dishIngredientInfos: [],
            },
            {
              id: 62694,
              name: '家常拍黄瓜',
              marketPrice: 0,
              leastCellNum: 1,
              isReplace: false,
              isDefault: false,
              isMulti: false,
              brandDishId: 139068,
              dishQty: 1,
              boxQty: 1,
              dishPropertyTypeInfos: [],
              dishIngredientInfos: [],
            },
          ],
        },
      ],
    },
  ],
  groups: [
    {
      id: 26363,
      name: '默认分组',
      orderMin: 0,
      orderMax: 2,
      childInfos: [
        {
          id: 938230,
          name: '西葫芦鸡蛋蒸饺(6只)',
          marketPrice: 0,
          leastCellNum: 1,
          isReplace: false,
          isDefault: false,
          isMulti: false,
          brandDishId: 694575,
          dishQty: 1,
          boxQty: 1,
          dishPropertyTypeInfos: [],
          dishIngredientInfos: [],
        },
        {
          id: 1218630,
          name: '应季美味蒸饺(6只)',
          marketPrice: 0,
          leastCellNum: 1,
          isReplace: false,
          isDefault: false,
          isMulti: true,
          brandDishId: 877587,
          dishQty: 1,
          boxQty: 1,
          dishPropertyTypeInfos: [],
          dishIngredientInfos: [],
        },
      ],
    },
    {
      id: 26365,
      name: '小吃饮品',
      orderMin: 0,
      orderMax: 1,
      childInfos: [
        {
          id: 62891,
          name: '竹蔗茅根马蹄水(冷)',
          marketPrice: 0,
          leastCellNum: 1,
          isReplace: false,
          isDefault: false,
          isMulti: true,
          brandDishId: 139139,
          dishQty: 1,
          boxQty: 1,
          dishPropertyTypeInfos: [],
          dishIngredientInfos: [],
        },
        {
          id: 62685,
          name: '爽口脆萝卜',
          marketPrice: 0,
          leastCellNum: 1,
          isReplace: false,
          isDefault: false,
          isMulti: false,
          brandDishId: 138991,
          dishQty: 1,
          boxQty: 1,
          dishPropertyTypeInfos: [],
          dishIngredientInfos: [],
        },
        {
          id: 62694,
          name: '家常拍黄瓜',
          marketPrice: 0,
          leastCellNum: 1,
          isReplace: false,
          isDefault: false,
          isMulti: false,
          brandDishId: 139068,
          dishQty: 1,
          boxQty: 1,
          dishPropertyTypeInfos: [],
          dishIngredientInfos: [],
        },
      ],
    },
  ],
};

exports.orderedSingleDishesAndGroupDishes = [{
  type: 2,
  order: 3,
  dishPropertyTypeInfos: [],
}, {
  type: 1,
  order: [{
    id: 99991,
    count: 3,
  }, {
    id: 99992,
    count: 4,
  }],
}, {
  id: 99993,
}];

exports.orderedSingleDishesOnly = [{
  type: 3,
  order: 6,
  dishPropertyTypeInfos: [],
}, {
  type: 4,
  order: 4,
  dishPropertyTypeInfos: [],
}, {
  id: 99991,
}, {
  id: 99992,
}, {
  id: 99993,
}];

exports.orderedGroupDishesOnly = [{
  id: 99993,
}, {
  type: 1,
  order: [{
    id: 99991,
    count: 1,
  }, {
    id: 99992,
    count: 2,
  }],
}, {
  type: 1,
  order: [{
    id: 99991,
    count: 3,
  }, {
    id: 99992,
    count: 4,
  }],
}];
