#!/bin/bash
if [ $1 = "test" ]
then
  echo "Build testing release..."
  export NODE_ENV="production"
  export PROD_HOST="testweixin.shishike.com"
  webpack --progress -p --config webpack.config.production.js
elif [ $1 = "gld" ]
then
  echo "Build gld release..."
  NODE_ENV="production"
  PROD_HOST="gld.weixin.shishike.com"
  webpack --progress -p --config webpack.config.production.js
elif [ $1 = 'clean' ]
then
  echo "Clean all local releases..."
  rm -fr dist-*
else
  echo "Usage: build test | gld | clean"
fi
