#!/bin/bash
if [ $1 = "test" ]
then
  echo "Build testing release..."
  export NODE_ENV="production"
  export PROD_HOST="testweixin.shishike.com"
  webpack --progress -p --config webpack.config.production.js
elif [ $1 = "gld" ]
then
  echo "Build gld release..."
  export NODE_ENV="production"
  export PROD_HOST="gld.weixin.keruyun.com"
  webpack --progress -p --config webpack.config.production.js
elif [ $1 = 'dev' ]
then
  echo "Build dev release..."
  export NODE_ENV="production"
  export PROD_HOST="devweixin.shishike.com"
  webpack --progress -p --config webpack.config.production.js
elif [ $1 = 'prod' ]
then
  echo "Build prod release..."
  export NODE_ENV="production"
  export PROD_HOST="weixin.keruyun.com"
  webpack --progress -p --config webpack.config.production.js
elif [ $1 = 'clean' ]
then
  echo "Clean all local releases..."
  rm -fr dist-*
else
  echo "Usage: build test | gld | prod | clean"
fi
